### ISSUE TITLE
级长选举（试行）

### ISSUE THREAD

**Issue by Peresh** [Peresh/hogwarts_forum#10]
由于男女学生会主席事务繁忙，校友日渐增多，为了让群运行的更好，举办更多的活动，希望得到各院级长的协助，墙裂邀请有时间有精力有激情有爱心啥都有的各位同学参选级长，散发你的热量吧~

1. 选举方式
    - 候选同学：有意参选级长的同学在该issue下留言，留言内容包括：
        1. 学院-昵称
        2. 参选留言（参选理由、个人优势等）
    - 选举同学：为候选人投票
        - 投票方式：点击该候选同学留言右上角或左下角的**笑脸表情**，选择**大拇指表情**为他/她投票。
    - 结算方式：各学院得票第一的男同学，得票第一的女同学，两位就任级长（如出现单一性别情况，结算时选举得票前两名同学担任）
    - 投票截止日期：2017-08-20 周日 24：00，周一由男女学生会主席进行统计（Griffindor-PereshCh, Ravenclaw-Jessica）
    - 级长任期：暂定至2017-08-31，视试行情况再议连任或进行下一任选举

2. 级长权利:
    - 加减学院分（暂未开放）
    - 组织各项活动（学院杯，联谊，面基，相亲，聚会等）
    - 监督举报违反群纪律的行为

3. 级长义务：
    - 迎接新同学
    - 为其他同学力所能及的帮助，答疑解惑等
    - 协助男女学生会主席管理微信群，建设优质和谐校园

4. 意见建议欢迎联系男女学生会主席补充

**Comment by Ravenclow-Chris** [comment]
Ravenclaw-chris 
理由:为人民服务
优势:随和

**Comment by OldNineEmmmm** [comment]
a.Ravenclaw-Nine
b.羞答答脸
   参选理由呢 就是想跟各位小兔崽子们以后有多交流的机会 对一些陌生的领域可以得到新的认知 同时也把我自己的所懂所学告诉大家 能为这个日益壮大的大大大家庭贡献一点我自己的微薄之力
   个人优势呀 作为一名90后的游戏迷和金融汪 上班不太忙的时候基本都是静静的盯着群里消息 最大的特点就是有爱心呀 尤其是在各位小可爱们郁闷无法化解的时候欢迎投入我的怀抱 继续羞答答一次 希望大家90后空巢老人一次温暖你们的机会 笔芯💗

**Comment by 2333Eve** [comment]
Slytherin-Eva
理由：。。。协助我家教授工作？。。。
优势：斯内普教授的小娇妻？
。。。我来凑人数请无视我）

**Comment by FISH1116** [comment]
a.Ravenclaw-Panda胖哒
b.喜欢热闹喜欢办活动
胖哒虽然最近在考试但考完试之后会弄个学院杯希望大家都能参加哟~因为群里新人越来越多啦，但是感觉没有什么固定活动维系大家感情所以好多人潜水，所以希望弄些小活动，让群里的大家都变得更熟悉。希望新人进群能融入大家，还有希望这个几月闭关学习的bo，ast，piko还有很多人，回来的时候群里依然能热热闹闹的。

**Comment by SlytherinMorticia** [comment]
Slytherin-Morticia
理由：希望大家可以加入食死徒
优势：我也是凑人数的没打算竞选，来这里主要是想公屏表白我们家Tom.Riddle.Jr，希望大家可以多多支持我们食死徒大军，谢谢cctv，谢谢霍格TV！

**Comment by Monster23333** [comment]
a.Hufflepuff-Monster
b.好好学习，天天向上
我也没打算参加竞选
高中生一枚，不是假期就很少上线啦~
所以我就又是一个来凑数的啦~

**Comment by RuiZ404** [comment]
a.Gryffindor-Kido
b.参选理由：弥补一下狮院的空白😂希望小伙伴们再接再厉，主要是凑数？
优势：∠( ᐛ 」∠)＿级长这种身份听起来就很高冷很男神啊可以的话请给狮院一个冰山男神的级长来宠爱我好吗！（住口）
咳嗯目前最激动的一点是看到级长可以搞事情（划掉）组织活动…举手报名策划！我真的是学（guo）这个的！！三年后约一波北京环球的霍格沃茨群聚呀！！！

**Comment by Gryffindoranna** [comment]
a.Gryffindor-anna
b.资深哈迷一枚~作为小狮子，想满足一下一直以来想当级长的心理?(不)咳咳，我我我是为了这个霍格沃茨大家庭和咱们狮院的未来做出伟大贡献(迷)啊!(* ॑꒳ ॑* )⋆*(狮子座的我忍不住233)嗯，也非常希望我们可以着手举办一个大大的哈迷爬梯~个人优势哈就是比较耐心，可以带领新的小狮子们一起造反(啊不是)一起熟悉新环境~哦哦~回看的时候发现了相亲~(滑稽脸)总之很期待以后越来越完善的学院系统和级长搞事|･ω･｀)(写到这里才发现自己好像并不会写个人简介233)
